sf: 4
model:
  base_learning_rate: 5.0e-05
  target: ldm.models.diffusion.ddpm_wavelet.LatentDiffusionWaveletCS
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: lq_image
    cond_stage_key: image
    # conditioning_key: concat_struct
    conditioning_key: concat

    image_size: 512
    channels: 16 ##
    cond_stage_trainable: True

    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    # ckpt_path: null
    ckpt_path: ckpt/KLz16emb16_merge_fix.ckpt
    only_model: False
    # ignore_keys: ["model.diffusion_model.input_blocks.0.0","model.diffusion_model.out.0"]
    ignore_keys:
      - model.diffusion_model.input_blocks.0.0.weight
      - model.diffusion_model.input_blocks.0.0.bias
      - model.diffusion_model.out.0.weight
      - model.diffusion_model.out.0.bias

    unfrozen_first_stage: False
    unfrozen_unet: False
    unfrozen_cond_stage: True

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModelDualcondV2
      params:
        image_size: 32
        in_channels: 32
        out_channels: 16
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_head_channels: 64
        use_spatial_transformer: False
        use_linear_in_transformer: True
        transformer_depth: 1
        # context_dim: None
        use_checkpoint: False
        legacy: False
        semb_channels: 256

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        # ckpt_path: logs/2025-07-21T16-02-12_AutoencoderKL_z16/checkpoints/last.ckpt
        embed_dim: 16
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 16
          resolution: 512
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.models.cond_stage_UNet.EncoderUNet
      params:
        image_size: 128 # 你小波图的输入分辨率
        in_channels: 4 # 小波子带数
        model_channels: 64 # 初始通道数，推荐64或128
        out_channels: 256 # 输出给 SPADE 每层的特征通道数
        num_res_blocks: 3
        attention_resolutions: [64, 32, 16, 8] # 哪些分辨率上加入AttentionBlock
        channel_mult: [1, 2, 4, 8, 8, 8] # 每层通道增长倍数（建议4层）
        dropout: 0.0
        use_checkpoint: False
        use_fp16: False
        use_scale_shift_norm: True

    structcond_stage_config:
      target: ldm.modules.diffusionmodules.openaimodel.EncoderUNetModelWT
      params:
        image_size: 96
        in_channels: 4
        model_channels: 256
        out_channels: 256
        num_res_blocks: 2
        attention_resolutions: [4, 2, 1]
        dropout: 0
        channel_mult: [1, 1, 2, 2]
        conv_resample: True
        dims: 2
        use_checkpoint: False
        use_fp16: False
        num_heads: 4
        num_head_channels: -1
        num_heads_upsample: -1
        use_scale_shift_norm: False
        resblock_updown: False
        use_new_attention_order: False
        use_spatial_transformer: False

degradation:
  use_jpeg: False
  resize_prob: [0.2, 0.7, 0.1]
  resize_range: [0.3, 1.5]
  gaussian_noise_prob: 0.5
  noise_range: [1, 15]
  poisson_scale_range: [0.05, 2.0]
  gray_noise_prob: 0.4
  jpeg_range: [60, 95]
  second_blur_prob: 0.5
  resize_prob2: [0.3, 0.4, 0.3]
  resize_range2: [0.6, 1.2]
  gaussian_noise_prob2: 0.5
  noise_range2: [1, 12]
  poisson_scale_range2: [0.05, 1.0]
  gray_noise_prob2: 0.4
  jpeg_range2: [60, 100]
  gt_size: 512
  no_degradation_prob: 0.01

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 6
    wrap: false
    train:
      target: basicsr.data.wavelet_dataset.WaveletSRDataset
      params:
        image_type: png
        gt_path: "/home/flyingbucket/DataStore/WHU_512"
        crop_size: 512
        io_backend:
          type: disk
        gt_size: 512
        use_hflip: True
        use_rot: False

    validation:
      target: basicsr.data.wavelet_dataset.WaveletSRDataset
      params:
        image_type: png
        gt_path: "/home/flyingbucket/DataStore/WHU_512_small"
        crop_size: 512
        io_backend:
          type: disk
        gt_size: 512
        use_hflip: True
        use_rot: False

test_data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 6
    wrap: false
    test:
      target: basicsr.data.wavelet_dataset.WaveletSRDataset
      params:
        gt_path: "/home/flyingbucket/DataStore/WHU_512_small"
        image_type: png
        crop_size: 512
        io_backend:
          type: disk
        gt_size: 512
        use_hflip: False
        use_rot: False

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1500
        max_images: 4
        increase_log_steps: False

  trainer:
    gpus: [2]
    benchmark: True
    max_steps: 800000
    accumulate_grad_batches: 6
    accelerator: ddp
