model:
  base_learning_rate: 5.0e-5
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    # for training only
    # ckpt_path: /mnt/lustre/jywang/code/stable_diffmodels/v2-1_512-ema-pruned.ckpt
    monitor: "val/rec_loss"
    embed_dim: 4
    # fusion_w: 1.0
    # freeze_dec: True
    # synthesis_data: False
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 1e6
        kl_weight: 0
        disc_weight: 0.025
        disc_factor: 1.0
        disc_in_channels: 1
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 512
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    image_key: 'gt'


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 12
    wrap: True
    train:
      target: basicsr.data.autoencoderGT_dataset.AutoencoderImageDataset
      params:
        gt_path: "/home/flyingbucket/DataStore/WHU_512"
        io_backend:
          type: disk
        color: gray
    validation:
      target: basicsr.data.autoencoderGT_dataset.AutoencoderImageDataset
      params:
        gt_path: "/home/flyingbucket/DataStore/WHU_512_small"
        io_backend:
          type: disk
        color: gray

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1500
        max_images: 4
        increase_log_steps: False

  trainer:
    benchmark: True
    max_steps: 100000
    accumulate_grad_batches: 4
    gpus: [0]
    precision: 16